/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed": "#221b00",
              "background": "#10131a",
              "surface-container-lowest": "#0b0e14",
              "inverse-primary": "#00696f",
              "on-background": "#e1e2eb",
              "on-tertiary-fixed-variant": "#554500",
              "on-primary-fixed": "#002022",
              "tertiary-fixed": "#ffe173",
              "on-secondary-fixed": "#2c0051",
              "primary": "#e1fdff",
              "tertiary-fixed-dim": "#e8c423",
              "on-secondary-fixed-variant": "#6700b5",
              "secondary-fixed-dim": "#dcb8ff",
              "primary-fixed": "#74f5ff",
              "tertiary-container": "#fed83a",
              "inverse-on-surface": "#2e3037",
              "surface-tint": "#00dbe7",
              "surface": "#10131a",
              "on-surface-variant": "#b9cacb",
              "surface-container-highest": "#32353c",
              "on-tertiary": "#3b2f00",
              "primary-container": "#00f2ff",
              "secondary": "#dcb8ff",
              "outline-variant": "#3a494b",
              "error": "#ffb4ab",
              "primary-fixed-dim": "#00dbe7",
              "on-primary-container": "#006a71",
              "on-tertiary-container": "#725e00",
              "on-primary": "#00363a",
              "surface-container-low": "#191c22",
              "surface-variant": "#32353c",
              "surface-bright": "#363940",
              "on-secondary": "#480081",
              "on-surface": "#e1e2eb",
              "on-primary-fixed-variant": "#004f54",
              "secondary-fixed": "#efdbff",
              "outline": "#849495",
              "tertiary": "#fff6e4",
              "inverse-surface": "#e1e2eb",
              "error-container": "#93000a",
              "on-secondary-container": "#dcb7ff",
              "surface-container-high": "#272a31",
              "surface-container": "#1d2026",
              "on-error": "#690005",
              "secondary-container": "#7701d0",
              "surface-dim": "#10131a"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"],
              "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
      }
    },
  },
  plugins: [],
}
